"""empty message

Revision ID: ba1228206e10
Revises: 8685d1604979
Create Date: 2023-10-16 23:59:22.529843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba1228206e10'
down_revision = '8685d1604979'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('face_encoding')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('face_encoding', sa.BLOB(), nullable=False))

    # ### end Alembic commands ###
